# Generated by Django 4.2.15 on 2024-11-03 08:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0003_progress_grade_submission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="correct_answer",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="options",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="question",
        ),
        migrations.AddField(
            model_name="activity",
            name="activity_code",
            field=models.UUIDField(
                default=uuid.UUID("a768a438-11bc-4902-b31b-25875904a660"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="max_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activity",
            name="questions",
            field=models.JSONField(
                default={},
                help_text="List of questions with options and correct answers",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="quiz_type",
            field=models.CharField(
                default="",
                help_text="Type of quiz, e.g., 'multiple_choice'",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
