# Generated by Django 4.2.15 on 2024-11-03 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0004_remove_activity_correct_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="time_limit",
            field=models.IntegerField(
                default=6000, help_text="Time limit in seconds for the activity"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_code",
            field=models.UUIDField(
                default=uuid.UUID("3a9eef7a-2f8f-42ba-9d7a-f16e41d5f45c"),
                editable=False,
                unique=True,
            ),
        ),
    ]
