# Generated by Django 4.2.15 on 2024-11-04 03:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0005_activity_time_limit_alter_activity_activity_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="selected_option",
        ),
        migrations.AddField(
            model_name="submission",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_code",
            field=models.UUIDField(
                default=uuid.UUID("8a4aa390-f087-4f37-9fae-22c12500ece5"),
                editable=False,
                unique=True,
            ),
        ),
    ]
