# Generated by Django 4.2.15 on 2024-11-04 04:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0006_remove_submission_selected_option_submission_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="time_spent",
            field=models.IntegerField(
                default=1, help_text="Time spent in seconds to complete the activity"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_code",
            field=models.UUIDField(
                default=uuid.UUID("e2b66794-94a0-4b0a-8024-8cbd3dc72472"),
                editable=False,
                unique=True,
            ),
        ),
    ]
