# Generated by Django 4.2.15 on 2024-11-04 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0007_submission_time_spent_alter_activity_activity_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_code",
            field=models.UUIDField(
                default=uuid.UUID("0e911d33-e07e-4b63-b0dd-2ed10073999a"),
                editable=False,
                unique=True,
            ),
        ),
    ]
