# Generated by Django 4.2.15 on 2024-11-10 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0008_alter_activity_activity_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("multipleChoice", "Multiple Choice"),
                            ("sortableCode", "Sortable Code"),
                            ("tagMatcher", "Tag Matcher"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=50,
                    ),
                ),
                ("questions", models.JSONField(blank=True, null=True)),
                ("code_blocks", models.JSONField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_code",
            field=models.UUIDField(
                default=uuid.UUID("ef8e10a6-e68b-46a7-b353-a2a9f5e7c848"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="max_score",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(default="Beginner", max_length=50)),
                ("experience_points", models.IntegerField(default=0)),
                ("lives", models.IntegerField(default=3)),
                (
                    "games_played",
                    models.ManyToManyField(
                        blank=True, related_name="players", to="Models.game"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
