# Generated by Django 4.2.15 on 2024-11-10 04:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0009_game_alter_activity_activity_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_code",
            field=models.UUIDField(
                default=uuid.UUID("93216ac2-716c-4741-b6bc-947bbcd66ce3"),
                editable=False,
                unique=True,
            ),
        ),
    ]
