# Generated by Django 4.2.15 on 2024-11-18 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0010_playerprofile_points_alter_activity_activity_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="example",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_code",
            field=models.UUIDField(
                default=uuid.UUID("f01453be-8cd7-4df0-8453-e89896666b15"),
                editable=False,
                unique=True,
            ),
        ),
    ]
